language: go
go:
    - 1.3
    - 1.4
    - 1.5
    - 1.6
    - 1.6
    - 1.7
    - 1.8
    - 1.9
    - 1.10
    - tip
cache:
  #- apt: true

install:
  - sudo apt-get update -y
  - sudo apt-get install -y curl bison make

script:
  - go clean
  - make get-deps
  - make get-test-deps
  - go vet
  - go build
  - make check
  - make test-multi-cpu

  - # avoid excessive output
  - make bench 2> bench.log
  
  - time ./edify download_specs 14B
  - time ./edify extract_specs 14B
  - time ./edify purge_specs 14B
  - time ./edify parse testdata/UNCL.14B
  - time ./edify query --version 14B -d testdata/d14b/
  - time ./edify query  -d testdata/d14b/ 
  - time ./edify query  -d testdata/d14b/ --version 14B
  - time ./edify query  -d testdata/d14b/ -m testdata/messages/INVOIC_1.txt
  - time ./edify query  -d testdata/d14b/ -m testdata/messages/INVOIC_1.txt  -q "grp:Group_7[0]/seg:CUX[0]"
  # - time ./edify  parse testdata/EDED.14B
  # - time ./edify  parse testdata/EDCD.14B

  - make cover
